services:
  # The Background Worker runs the infinite Python data pipeline
  - type: worker
    name: greenpulse-pipeline
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main_pipeline.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  # The Web Service runs the FastAPI server
  - type: web
    name: greenpulse-api
    env: python
    buildCommand: "pip install -r requirements.txt && pip install uvicorn"
    startCommand: "python -m uvicorn rag.api_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
